language: python
branches:
  only:
    - master
    - add-tests
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libxml2-dev libxslt-dev libcurl4-openssl-dev python-pycurl python-dev
script: python setup.py install
